[package]
name = "pvault"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.3"
bincode = "2"
clap = {version = "4.5.40", features = ["derive"]}
rpassword = "7.4.0"
secrecy = "0.8"
subtle = "2.6.1"
zeroize = {version = "1.8.1", features = ["derive"]}
